---
driver:
<% case ENV['KITCHEN_DRIVER']
  when 'digitalocean' %>
    name: digitalocean
    region: fra1
    ipv6: true
    private_networking: true
    size: 512
  <% else %>
    name: vagrant
    customize:
      memory: 512
<% end %>

provisioner:
  name: chef_zero

platforms:
<% case ENV['KITCHEN_DRIVER']
  when 'digitalocean' %>
  - name: centos-7-2-x64
<% else %>
  - name: centos-7.2
<% end %>

suites:
  - name: default
    run_list:
      - recipe[freeradius::default]
